/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OneTimeMetering
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T09:23:54.867-04:00")



public class OneTimeMetering {
  @SerializedName("oneTimeFixedPrice")
  private Double oneTimeFixedPrice = null;

  public OneTimeMetering oneTimeFixedPrice(Double oneTimeFixedPrice) {
    this.oneTimeFixedPrice = oneTimeFixedPrice;
    return this;
  }

   /**
   * Get oneTimeFixedPrice
   * @return oneTimeFixedPrice
  **/
  @ApiModelProperty(value = "")
  public Double getOneTimeFixedPrice() {
    return oneTimeFixedPrice;
  }

  public void setOneTimeFixedPrice(Double oneTimeFixedPrice) {
    this.oneTimeFixedPrice = oneTimeFixedPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneTimeMetering oneTimeMetering = (OneTimeMetering) o;
    return Objects.equals(this.oneTimeFixedPrice, oneTimeMetering.oneTimeFixedPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oneTimeFixedPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneTimeMetering {\n");
    
    sb.append("    oneTimeFixedPrice: ").append(toIndentedString(oneTimeFixedPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

