/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PolicyStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T09:23:54.867-04:00")



public class PolicyStats {
  @SerializedName("conflictCount")
  private Long conflictCount = null;

  @SerializedName("enforcedCount")
  private Long enforcedCount = null;

  @SerializedName("notEnforcedCount")
  private Long notEnforcedCount = null;

  public PolicyStats conflictCount(Long conflictCount) {
    this.conflictCount = conflictCount;
    return this;
  }

   /**
   * Get conflictCount
   * @return conflictCount
  **/
  @ApiModelProperty(value = "")
  public Long getConflictCount() {
    return conflictCount;
  }

  public void setConflictCount(Long conflictCount) {
    this.conflictCount = conflictCount;
  }

  public PolicyStats enforcedCount(Long enforcedCount) {
    this.enforcedCount = enforcedCount;
    return this;
  }

   /**
   * Get enforcedCount
   * @return enforcedCount
  **/
  @ApiModelProperty(value = "")
  public Long getEnforcedCount() {
    return enforcedCount;
  }

  public void setEnforcedCount(Long enforcedCount) {
    this.enforcedCount = enforcedCount;
  }

  public PolicyStats notEnforcedCount(Long notEnforcedCount) {
    this.notEnforcedCount = notEnforcedCount;
    return this;
  }

   /**
   * Get notEnforcedCount
   * @return notEnforcedCount
  **/
  @ApiModelProperty(value = "")
  public Long getNotEnforcedCount() {
    return notEnforcedCount;
  }

  public void setNotEnforcedCount(Long notEnforcedCount) {
    this.notEnforcedCount = notEnforcedCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyStats policyStats = (PolicyStats) o;
    return Objects.equals(this.conflictCount, policyStats.conflictCount) &&
        Objects.equals(this.enforcedCount, policyStats.enforcedCount) &&
        Objects.equals(this.notEnforcedCount, policyStats.notEnforcedCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conflictCount, enforcedCount, notEnforcedCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyStats {\n");
    
    sb.append("    conflictCount: ").append(toIndentedString(conflictCount)).append("\n");
    sb.append("    enforcedCount: ").append(toIndentedString(enforcedCount)).append("\n");
    sb.append("    notEnforcedCount: ").append(toIndentedString(notEnforcedCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

