/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.virtualviking.vra.jenkinsplugin.model.catalog.FormDefinition;

/**
 * ResourceAction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T09:23:54.867-04:00")



public class ResourceAction {
  /**
   * Resource action type
   */
  @JsonAdapter(ActionTypeEnum.Adapter.class)
  public enum ActionTypeEnum {
    ACTION("RESOURCE_ACTION"),
    
    EXTENSION("RESOURCE_EXTENSION");

    private String value;

    ActionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActionTypeEnum fromValue(String text) {
      for (ActionTypeEnum b : ActionTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ActionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ActionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ActionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ActionTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("actionType")
  private ActionTypeEnum actionType = null;

  @SerializedName("dependents")
  private List<String> dependents = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("displayName")
  private String displayName = null;

  @SerializedName("formDefinition")
  private FormDefinition formDefinition = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("orgId")
  private String orgId = null;

  @SerializedName("projectId")
  private String projectId = null;

  @SerializedName("schema")
  private Object schema = null;

  @SerializedName("valid")
  private Boolean valid = null;

  public ResourceAction actionType(ActionTypeEnum actionType) {
    this.actionType = actionType;
    return this;
  }

   /**
   * Resource action type
   * @return actionType
  **/
  @ApiModelProperty(value = "Resource action type")
  public ActionTypeEnum getActionType() {
    return actionType;
  }

  public void setActionType(ActionTypeEnum actionType) {
    this.actionType = actionType;
  }

  public ResourceAction dependents(List<String> dependents) {
    this.dependents = dependents;
    return this;
  }

  public ResourceAction addDependentsItem(String dependentsItem) {
    if (this.dependents == null) {
      this.dependents = new ArrayList<String>();
    }
    this.dependents.add(dependentsItem);
    return this;
  }

   /**
   * Dependent resources
   * @return dependents
  **/
  @ApiModelProperty(value = "Dependent resources")
  public List<String> getDependents() {
    return dependents;
  }

  public void setDependents(List<String> dependents) {
    this.dependents = dependents;
  }

  public ResourceAction description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Resource action description
   * @return description
  **/
  @ApiModelProperty(value = "Resource action description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ResourceAction displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Resource action display name
   * @return displayName
  **/
  @ApiModelProperty(value = "Resource action display name")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ResourceAction formDefinition(FormDefinition formDefinition) {
    this.formDefinition = formDefinition;
    return this;
  }

   /**
   * Resource action custom UI definition. Optional
   * @return formDefinition
  **/
  @ApiModelProperty(value = "Resource action custom UI definition. Optional")
  public FormDefinition getFormDefinition() {
    return formDefinition;
  }

  public void setFormDefinition(FormDefinition formDefinition) {
    this.formDefinition = formDefinition;
  }

  public ResourceAction id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Resource action id
   * @return id
  **/
  @ApiModelProperty(value = "Resource action id")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ResourceAction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Resource action name
   * @return name
  **/
  @ApiModelProperty(value = "Resource action name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResourceAction orgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

   /**
   * Resource action org ID
   * @return orgId
  **/
  @ApiModelProperty(value = "Resource action org ID")
  public String getOrgId() {
    return orgId;
  }

  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }

  public ResourceAction projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Resource action project ID
   * @return projectId
  **/
  @ApiModelProperty(value = "Resource action project ID")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public ResourceAction schema(Object schema) {
    this.schema = schema;
    return this;
  }

   /**
   * Resource action input schema
   * @return schema
  **/
  @ApiModelProperty(value = "Resource action input schema")
  public Object getSchema() {
    return schema;
  }

  public void setSchema(Object schema) {
    this.schema = schema;
  }

  public ResourceAction valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Resource action is valid for current state
   * @return valid
  **/
  @ApiModelProperty(value = "Resource action is valid for current state")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResourceAction resourceAction = (ResourceAction) o;
    return Objects.equals(this.actionType, resourceAction.actionType) &&
        Objects.equals(this.dependents, resourceAction.dependents) &&
        Objects.equals(this.description, resourceAction.description) &&
        Objects.equals(this.displayName, resourceAction.displayName) &&
        Objects.equals(this.formDefinition, resourceAction.formDefinition) &&
        Objects.equals(this.id, resourceAction.id) &&
        Objects.equals(this.name, resourceAction.name) &&
        Objects.equals(this.orgId, resourceAction.orgId) &&
        Objects.equals(this.projectId, resourceAction.projectId) &&
        Objects.equals(this.schema, resourceAction.schema) &&
        Objects.equals(this.valid, resourceAction.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actionType, dependents, description, displayName, formDefinition, id, name, orgId, projectId, schema, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResourceAction {\n");
    
    sb.append("    actionType: ").append(toIndentedString(actionType)).append("\n");
    sb.append("    dependents: ").append(toIndentedString(dependents)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    formDefinition: ").append(toIndentedString(formDefinition)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    schema: ").append(toIndentedString(schema)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

