/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.virtualviking.vra.jenkinsplugin.model.catalog.TagBasedMetering;

/**
 * TagBasedMeteringItem
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T09:23:54.867-04:00")



public class TagBasedMeteringItem {
  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("tagBasedMeterings")
  private List<TagBasedMetering> tagBasedMeterings = null;

  public TagBasedMeteringItem itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

   /**
   * Get itemName
   * @return itemName
  **/
  @ApiModelProperty(value = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public TagBasedMeteringItem tagBasedMeterings(List<TagBasedMetering> tagBasedMeterings) {
    this.tagBasedMeterings = tagBasedMeterings;
    return this;
  }

  public TagBasedMeteringItem addTagBasedMeteringsItem(TagBasedMetering tagBasedMeteringsItem) {
    if (this.tagBasedMeterings == null) {
      this.tagBasedMeterings = new ArrayList<TagBasedMetering>();
    }
    this.tagBasedMeterings.add(tagBasedMeteringsItem);
    return this;
  }

   /**
   * Get tagBasedMeterings
   * @return tagBasedMeterings
  **/
  @ApiModelProperty(value = "")
  public List<TagBasedMetering> getTagBasedMeterings() {
    return tagBasedMeterings;
  }

  public void setTagBasedMeterings(List<TagBasedMetering> tagBasedMeterings) {
    this.tagBasedMeterings = tagBasedMeterings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagBasedMeteringItem tagBasedMeteringItem = (TagBasedMeteringItem) o;
    return Objects.equals(this.itemName, tagBasedMeteringItem.itemName) &&
        Objects.equals(this.tagBasedMeterings, tagBasedMeteringItem.tagBasedMeterings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, tagBasedMeterings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagBasedMeteringItem {\n");
    
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    tagBasedMeterings: ").append(toIndentedString(tagBasedMeterings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

