/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.virtualviking.vra.jenkinsplugin.model.catalog.OneTimeMetering;

/**
 * TagBasedOneTimeMetering
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T09:23:54.867-04:00")



public class TagBasedOneTimeMetering {
  @SerializedName("key")
  private String key = null;

  @SerializedName("oneTimeMetering")
  private OneTimeMetering oneTimeMetering = null;

  @SerializedName("value")
  private String value = null;

  public TagBasedOneTimeMetering key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @ApiModelProperty(value = "")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public TagBasedOneTimeMetering oneTimeMetering(OneTimeMetering oneTimeMetering) {
    this.oneTimeMetering = oneTimeMetering;
    return this;
  }

   /**
   * Get oneTimeMetering
   * @return oneTimeMetering
  **/
  @ApiModelProperty(value = "")
  public OneTimeMetering getOneTimeMetering() {
    return oneTimeMetering;
  }

  public void setOneTimeMetering(OneTimeMetering oneTimeMetering) {
    this.oneTimeMetering = oneTimeMetering;
  }

  public TagBasedOneTimeMetering value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagBasedOneTimeMetering tagBasedOneTimeMetering = (TagBasedOneTimeMetering) o;
    return Objects.equals(this.key, tagBasedOneTimeMetering.key) &&
        Objects.equals(this.oneTimeMetering, tagBasedOneTimeMetering.oneTimeMetering) &&
        Objects.equals(this.value, tagBasedOneTimeMetering.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, oneTimeMetering, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagBasedOneTimeMetering {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    oneTimeMetering: ").append(toIndentedString(oneTimeMetering)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

