/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Href
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-09T18:26:35.661905-04:00[America/New_York]")
public class Href {
  @SerializedName("hrefs")
  private List<String> hrefs = null;

  @SerializedName("href")
  private String href = null;

  public Href hrefs(List<String> hrefs) {
    this.hrefs = hrefs;
    return this;
  }

  public Href addHrefsItem(String hrefsItem) {
    if (this.hrefs == null) {
      this.hrefs = new ArrayList<String>();
    }
    this.hrefs.add(hrefsItem);
    return this;
  }

   /**
   * Get hrefs
   * @return hrefs
  **/
  @Schema(description = "")
  public List<String> getHrefs() {
    return hrefs;
  }

  public void setHrefs(List<String> hrefs) {
    this.hrefs = hrefs;
  }

  public Href href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @Schema(description = "")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Href href = (Href) o;
    return Objects.equals(this.hrefs, href.hrefs) &&
        Objects.equals(this.href, href.href);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hrefs, href);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Href {\n");
    
    sb.append("    hrefs: ").append(toIndentedString(hrefs)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
