/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ScheduledExecutorService
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-09T18:26:35.661905-04:00[America/New_York]")
public class ScheduledExecutorService {
  @SerializedName("terminated")
  private Boolean terminated = null;

  @SerializedName("shutdown")
  private Boolean shutdown = null;

  public ScheduledExecutorService terminated(Boolean terminated) {
    this.terminated = terminated;
    return this;
  }

   /**
   * Get terminated
   * @return terminated
  **/
  @Schema(description = "")
  public Boolean isTerminated() {
    return terminated;
  }

  public void setTerminated(Boolean terminated) {
    this.terminated = terminated;
  }

  public ScheduledExecutorService shutdown(Boolean shutdown) {
    this.shutdown = shutdown;
    return this;
  }

   /**
   * Get shutdown
   * @return shutdown
  **/
  @Schema(description = "")
  public Boolean isShutdown() {
    return shutdown;
  }

  public void setShutdown(Boolean shutdown) {
    this.shutdown = shutdown;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScheduledExecutorService scheduledExecutorService = (ScheduledExecutorService) o;
    return Objects.equals(this.terminated, scheduledExecutorService.terminated) &&
        Objects.equals(this.shutdown, scheduledExecutorService.shutdown);
  }

  @Override
  public int hashCode() {
    return Objects.hash(terminated, shutdown);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScheduledExecutorService {\n");
    
    sb.append("    terminated: ").append(toIndentedString(terminated)).append("\n");
    sb.append("    shutdown: ").append(toIndentedString(shutdown)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
