/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.iaas;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/** ServiceStat */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:26:35.661905-04:00[America/New_York]")
public class ServiceStat {
  @SerializedName("unit")
  private String unit = null;

  @SerializedName("serviceReference")
  private String serviceReference = null;

  @SerializedName("kind")
  private String kind = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("lastUpdateMicrosUtc")
  private Long lastUpdateMicrosUtc = null;

  @SerializedName("sourceTimeMicrosUtc")
  private Long sourceTimeMicrosUtc = null;

  @SerializedName("timeSeriesStats")
  private TimeSeriesStats timeSeriesStats = null;

  @SerializedName("latestValue")
  private Double latestValue = null;

  @SerializedName("accumulatedValue")
  private Double accumulatedValue = null;

  @SerializedName("version")
  private Long version = null;

  @SerializedName("logHistogram")
  private ServiceStatLogHistogram logHistogram = null;

  public ServiceStat unit(String unit) {
    this.unit = unit;
    return this;
  }

  /**
   * Get unit
   *
   * @return unit
   */
  @Schema(description = "")
  public String getUnit() {
    return unit;
  }

  public void setUnit(String unit) {
    this.unit = unit;
  }

  public ServiceStat serviceReference(String serviceReference) {
    this.serviceReference = serviceReference;
    return this;
  }

  /**
   * Get serviceReference
   *
   * @return serviceReference
   */
  @Schema(description = "")
  public String getServiceReference() {
    return serviceReference;
  }

  public void setServiceReference(String serviceReference) {
    this.serviceReference = serviceReference;
  }

  public ServiceStat kind(String kind) {
    this.kind = kind;
    return this;
  }

  /**
   * Get kind
   *
   * @return kind
   */
  @Schema(description = "")
  public String getKind() {
    return kind;
  }

  public void setKind(String kind) {
    this.kind = kind;
  }

  public ServiceStat name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   *
   * @return name
   */
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ServiceStat lastUpdateMicrosUtc(Long lastUpdateMicrosUtc) {
    this.lastUpdateMicrosUtc = lastUpdateMicrosUtc;
    return this;
  }

  /**
   * Get lastUpdateMicrosUtc
   *
   * @return lastUpdateMicrosUtc
   */
  @Schema(description = "")
  public Long getLastUpdateMicrosUtc() {
    return lastUpdateMicrosUtc;
  }

  public void setLastUpdateMicrosUtc(Long lastUpdateMicrosUtc) {
    this.lastUpdateMicrosUtc = lastUpdateMicrosUtc;
  }

  public ServiceStat sourceTimeMicrosUtc(Long sourceTimeMicrosUtc) {
    this.sourceTimeMicrosUtc = sourceTimeMicrosUtc;
    return this;
  }

  /**
   * Get sourceTimeMicrosUtc
   *
   * @return sourceTimeMicrosUtc
   */
  @Schema(description = "")
  public Long getSourceTimeMicrosUtc() {
    return sourceTimeMicrosUtc;
  }

  public void setSourceTimeMicrosUtc(Long sourceTimeMicrosUtc) {
    this.sourceTimeMicrosUtc = sourceTimeMicrosUtc;
  }

  public ServiceStat timeSeriesStats(TimeSeriesStats timeSeriesStats) {
    this.timeSeriesStats = timeSeriesStats;
    return this;
  }

  /**
   * Get timeSeriesStats
   *
   * @return timeSeriesStats
   */
  @Schema(description = "")
  public TimeSeriesStats getTimeSeriesStats() {
    return timeSeriesStats;
  }

  public void setTimeSeriesStats(TimeSeriesStats timeSeriesStats) {
    this.timeSeriesStats = timeSeriesStats;
  }

  public ServiceStat latestValue(Double latestValue) {
    this.latestValue = latestValue;
    return this;
  }

  /**
   * Get latestValue
   *
   * @return latestValue
   */
  @Schema(description = "")
  public Double getLatestValue() {
    return latestValue;
  }

  public void setLatestValue(Double latestValue) {
    this.latestValue = latestValue;
  }

  public ServiceStat accumulatedValue(Double accumulatedValue) {
    this.accumulatedValue = accumulatedValue;
    return this;
  }

  /**
   * Get accumulatedValue
   *
   * @return accumulatedValue
   */
  @Schema(description = "")
  public Double getAccumulatedValue() {
    return accumulatedValue;
  }

  public void setAccumulatedValue(Double accumulatedValue) {
    this.accumulatedValue = accumulatedValue;
  }

  public ServiceStat version(Long version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   *
   * @return version
   */
  @Schema(description = "")
  public Long getVersion() {
    return version;
  }

  public void setVersion(Long version) {
    this.version = version;
  }

  public ServiceStat logHistogram(ServiceStatLogHistogram logHistogram) {
    this.logHistogram = logHistogram;
    return this;
  }

  /**
   * Get logHistogram
   *
   * @return logHistogram
   */
  @Schema(description = "")
  public ServiceStatLogHistogram getLogHistogram() {
    return logHistogram;
  }

  public void setLogHistogram(ServiceStatLogHistogram logHistogram) {
    this.logHistogram = logHistogram;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceStat serviceStat = (ServiceStat) o;
    return Objects.equals(this.unit, serviceStat.unit)
        && Objects.equals(this.serviceReference, serviceStat.serviceReference)
        && Objects.equals(this.kind, serviceStat.kind)
        && Objects.equals(this.name, serviceStat.name)
        && Objects.equals(this.lastUpdateMicrosUtc, serviceStat.lastUpdateMicrosUtc)
        && Objects.equals(this.sourceTimeMicrosUtc, serviceStat.sourceTimeMicrosUtc)
        && Objects.equals(this.timeSeriesStats, serviceStat.timeSeriesStats)
        && Objects.equals(this.latestValue, serviceStat.latestValue)
        && Objects.equals(this.accumulatedValue, serviceStat.accumulatedValue)
        && Objects.equals(this.version, serviceStat.version)
        && Objects.equals(this.logHistogram, serviceStat.logHistogram);
  }

  @Override
  public int hashCode() {
    return Objects.hash(
        unit,
        serviceReference,
        kind,
        name,
        lastUpdateMicrosUtc,
        sourceTimeMicrosUtc,
        timeSeriesStats,
        latestValue,
        accumulatedValue,
        version,
        logHistogram);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceStat {\n");

    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    serviceReference: ").append(toIndentedString(serviceReference)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    lastUpdateMicrosUtc: ")
        .append(toIndentedString(lastUpdateMicrosUtc))
        .append("\n");
    sb.append("    sourceTimeMicrosUtc: ")
        .append(toIndentedString(sourceTimeMicrosUtc))
        .append("\n");
    sb.append("    timeSeriesStats: ").append(toIndentedString(timeSeriesStats)).append("\n");
    sb.append("    latestValue: ").append(toIndentedString(latestValue)).append("\n");
    sb.append("    accumulatedValue: ").append(toIndentedString(accumulatedValue)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    logHistogram: ").append(toIndentedString(logHistogram)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
