/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.vra.jenkinsplugin.model.iaas.Tag;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * UpdateCloudAccountNsxTSpecification
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-09T18:26:35.661905-04:00[America/New_York]")
public class UpdateCloudAccountNsxTSpecification {
  @SerializedName("password")
  private String password = null;

  @SerializedName("associatedCloudAccountIds")
  private List<String> associatedCloudAccountIds = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("tags")
  private List<Tag> tags = null;

  @SerializedName("username")
  private String username = null;

  public UpdateCloudAccountNsxTSpecification password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Password to authenticate with the cloud account
   * @return password
  **/
  @Schema(example = "LVJbZNAkPCJs", description = "Password to authenticate with the cloud account")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public UpdateCloudAccountNsxTSpecification associatedCloudAccountIds(List<String> associatedCloudAccountIds) {
    this.associatedCloudAccountIds = associatedCloudAccountIds;
    return this;
  }

  public UpdateCloudAccountNsxTSpecification addAssociatedCloudAccountIdsItem(String associatedCloudAccountIdsItem) {
    if (this.associatedCloudAccountIds == null) {
      this.associatedCloudAccountIds = new ArrayList<String>();
    }
    this.associatedCloudAccountIds.add(associatedCloudAccountIdsItem);
    return this;
  }

   /**
   * vSphere cloud accounts associated with this NSX-T cloud account.
   * @return associatedCloudAccountIds
  **/
  @Schema(example = "[ \"42f3e0d199d134755684cd935435a\" ]", description = "vSphere cloud accounts associated with this NSX-T cloud account.")
  public List<String> getAssociatedCloudAccountIds() {
    return associatedCloudAccountIds;
  }

  public void setAssociatedCloudAccountIds(List<String> associatedCloudAccountIds) {
    this.associatedCloudAccountIds = associatedCloudAccountIds;
  }

  public UpdateCloudAccountNsxTSpecification name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-friendly name used as an identifier in APIs that support this option.
   * @return name
  **/
  @Schema(description = "A human-friendly name used as an identifier in APIs that support this option.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateCloudAccountNsxTSpecification description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A human-friendly description.
   * @return description
  **/
  @Schema(description = "A human-friendly description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UpdateCloudAccountNsxTSpecification tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public UpdateCloudAccountNsxTSpecification addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * A set of tag keys and optional values to set on the Cloud Account
   * @return tags
  **/
  @Schema(example = "[{\"key\": \"env\", \"value\": \"dev\"}]", description = "A set of tag keys and optional values to set on the Cloud Account")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public UpdateCloudAccountNsxTSpecification username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Username to authenticate with the cloud account
   * @return username
  **/
  @Schema(example = "administrator@csp.local", description = "Username to authenticate with the cloud account")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCloudAccountNsxTSpecification updateCloudAccountNsxTSpecification = (UpdateCloudAccountNsxTSpecification) o;
    return Objects.equals(this.password, updateCloudAccountNsxTSpecification.password) &&
        Objects.equals(this.associatedCloudAccountIds, updateCloudAccountNsxTSpecification.associatedCloudAccountIds) &&
        Objects.equals(this.name, updateCloudAccountNsxTSpecification.name) &&
        Objects.equals(this.description, updateCloudAccountNsxTSpecification.description) &&
        Objects.equals(this.tags, updateCloudAccountNsxTSpecification.tags) &&
        Objects.equals(this.username, updateCloudAccountNsxTSpecification.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, associatedCloudAccountIds, name, description, tags, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCloudAccountNsxTSpecification {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    associatedCloudAccountIds: ").append(toIndentedString(associatedCloudAccountIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
