/*
 * VMware Cloud Assembly Blueprint API
 * A multi-cloud Blueprint API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-09-12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.blueprint;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * BlueprintTaskExecution
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-31T20:41:57.276-04:00")



public class BlueprintTaskExecution {
  @SerializedName("dependsOnTasks")
  private List<String> dependsOnTasks = null;

  @SerializedName("failureMessage")
  private String failureMessage = null;

  @SerializedName("inputProperties")
  private Object inputProperties = null;

  @SerializedName("outputProperties")
  private Object outputProperties = null;

  @SerializedName("resourceName")
  private String resourceName = null;

  @SerializedName("resourceType")
  private String resourceType = null;

  /**
   * Task status
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    CREATED("CREATED"),
    
    STARTED("STARTED"),
    
    FINISHED("FINISHED"),
    
    FAILED("FAILED"),
    
    CANCELLED("CANCELLED");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static StatusEnum fromValue(String text) {
      for (StatusEnum b : StatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return StatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("taskName")
  private String taskName = null;

   /**
   * Tasks depends on other tasks
   * @return dependsOnTasks
  **/
  @ApiModelProperty(value = "Tasks depends on other tasks")
  public List<String> getDependsOnTasks() {
    return dependsOnTasks;
  }

   /**
   * Task failure message
   * @return failureMessage
  **/
  @ApiModelProperty(value = "Task failure message")
  public String getFailureMessage() {
    return failureMessage;
  }

   /**
   * Task input properties
   * @return inputProperties
  **/
  @ApiModelProperty(value = "Task input properties")
  public Object getInputProperties() {
    return inputProperties;
  }

   /**
   * Task output properties
   * @return outputProperties
  **/
  @ApiModelProperty(value = "Task output properties")
  public Object getOutputProperties() {
    return outputProperties;
  }

   /**
   * Resource name
   * @return resourceName
  **/
  @ApiModelProperty(value = "Resource name")
  public String getResourceName() {
    return resourceName;
  }

   /**
   * Resource type
   * @return resourceType
  **/
  @ApiModelProperty(value = "Resource type")
  public String getResourceType() {
    return resourceType;
  }

   /**
   * Task status
   * @return status
  **/
  @ApiModelProperty(value = "Task status")
  public StatusEnum getStatus() {
    return status;
  }

   /**
   * Task name
   * @return taskName
  **/
  @ApiModelProperty(value = "Task name")
  public String getTaskName() {
    return taskName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlueprintTaskExecution blueprintTaskExecution = (BlueprintTaskExecution) o;
    return Objects.equals(this.dependsOnTasks, blueprintTaskExecution.dependsOnTasks) &&
        Objects.equals(this.failureMessage, blueprintTaskExecution.failureMessage) &&
        Objects.equals(this.inputProperties, blueprintTaskExecution.inputProperties) &&
        Objects.equals(this.outputProperties, blueprintTaskExecution.outputProperties) &&
        Objects.equals(this.resourceName, blueprintTaskExecution.resourceName) &&
        Objects.equals(this.resourceType, blueprintTaskExecution.resourceType) &&
        Objects.equals(this.status, blueprintTaskExecution.status) &&
        Objects.equals(this.taskName, blueprintTaskExecution.taskName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dependsOnTasks, failureMessage, inputProperties, outputProperties, resourceName, resourceType, status, taskName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlueprintTaskExecution {\n");
    
    sb.append("    dependsOnTasks: ").append(toIndentedString(dependsOnTasks)).append("\n");
    sb.append("    failureMessage: ").append(toIndentedString(failureMessage)).append("\n");
    sb.append("    inputProperties: ").append(toIndentedString(inputProperties)).append("\n");
    sb.append("    outputProperties: ").append(toIndentedString(outputProperties)).append("\n");
    sb.append("    resourceName: ").append(toIndentedString(resourceName)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    taskName: ").append(toIndentedString(taskName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

