/*
 * VMware Cloud Assembly Blueprint API
 * A multi-cloud Blueprint API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-09-12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.blueprint;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import net.virtualviking.vra.jenkinsplugin.model.blueprint.ContentSourceConfig;

/**
 * ContentSource
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-31T20:41:57.276-04:00")



public class ContentSource {
  @SerializedName("config")
  private ContentSourceConfig config = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("integrationAccountName")
  private String integrationAccountName = null;

  @SerializedName("isSyncEnabled")
  private Boolean isSyncEnabled = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("projectId")
  private String projectId = null;

  @SerializedName("typeId")
  private String typeId = null;

  public ContentSource config(ContentSourceConfig config) {
    this.config = config;
    return this;
  }

   /**
   * Get config
   * @return config
  **/
  @ApiModelProperty(value = "")
  public ContentSourceConfig getConfig() {
    return config;
  }

  public void setConfig(ContentSourceConfig config) {
    this.config = config;
  }

  public ContentSource description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ContentSource id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ContentSource integrationAccountName(String integrationAccountName) {
    this.integrationAccountName = integrationAccountName;
    return this;
  }

   /**
   * Get integrationAccountName
   * @return integrationAccountName
  **/
  @ApiModelProperty(value = "")
  public String getIntegrationAccountName() {
    return integrationAccountName;
  }

  public void setIntegrationAccountName(String integrationAccountName) {
    this.integrationAccountName = integrationAccountName;
  }

  public ContentSource isSyncEnabled(Boolean isSyncEnabled) {
    this.isSyncEnabled = isSyncEnabled;
    return this;
  }

   /**
   * Get isSyncEnabled
   * @return isSyncEnabled
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsSyncEnabled() {
    return isSyncEnabled;
  }

  public void setIsSyncEnabled(Boolean isSyncEnabled) {
    this.isSyncEnabled = isSyncEnabled;
  }

  public ContentSource label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public ContentSource name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ContentSource projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @ApiModelProperty(value = "")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }

  public ContentSource typeId(String typeId) {
    this.typeId = typeId;
    return this;
  }

   /**
   * Get typeId
   * @return typeId
  **/
  @ApiModelProperty(value = "")
  public String getTypeId() {
    return typeId;
  }

  public void setTypeId(String typeId) {
    this.typeId = typeId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContentSource contentSource = (ContentSource) o;
    return Objects.equals(this.config, contentSource.config) &&
        Objects.equals(this.description, contentSource.description) &&
        Objects.equals(this.id, contentSource.id) &&
        Objects.equals(this.integrationAccountName, contentSource.integrationAccountName) &&
        Objects.equals(this.isSyncEnabled, contentSource.isSyncEnabled) &&
        Objects.equals(this.label, contentSource.label) &&
        Objects.equals(this.name, contentSource.name) &&
        Objects.equals(this.projectId, contentSource.projectId) &&
        Objects.equals(this.typeId, contentSource.typeId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(config, description, id, integrationAccountName, isSyncEnabled, label, name, projectId, typeId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContentSource {\n");
    
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    integrationAccountName: ").append(toIndentedString(integrationAccountName)).append("\n");
    sb.append("    isSyncEnabled: ").append(toIndentedString(isSyncEnabled)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    typeId: ").append(toIndentedString(typeId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

