/*
 * VMware Cloud Assembly Blueprint API
 * A multi-cloud Blueprint API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-09-12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.blueprint;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OutputValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-08-31T20:41:57.276-04:00")



public class OutputValue {
  @SerializedName("description")
  private String description = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("sensitive")
  private Boolean sensitive = null;

  public OutputValue description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the output value in the Terraform configuration.
   * @return description
  **/
  @ApiModelProperty(value = "The description of the output value in the Terraform configuration.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public OutputValue name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the output value in the Terraform configuration.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the output value in the Terraform configuration.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OutputValue sensitive(Boolean sensitive) {
    this.sensitive = sensitive;
    return this;
  }

   /**
   * A flag indicating that the field should be obscured because of security concerns.
   * @return sensitive
  **/
  @ApiModelProperty(value = "A flag indicating that the field should be obscured because of security concerns.")
  public Boolean isSensitive() {
    return sensitive;
  }

  public void setSensitive(Boolean sensitive) {
    this.sensitive = sensitive;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputValue outputValue = (OutputValue) o;
    return Objects.equals(this.description, outputValue.description) &&
        Objects.equals(this.name, outputValue.name) &&
        Objects.equals(this.sensitive, outputValue.sensitive);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, name, sensitive);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputValue {\n");
    
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sensitive: ").append(toIndentedString(sensitive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

