/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.vra.jenkinsplugin.model.catalog.NamedMetering;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * NamedMeteringItem
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class NamedMeteringItem {
  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("namedMeterings")
  private List<NamedMetering> namedMeterings = null;

  public NamedMeteringItem itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

   /**
   * Get itemName
   * @return itemName
  **/
  @Schema(description = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public NamedMeteringItem namedMeterings(List<NamedMetering> namedMeterings) {
    this.namedMeterings = namedMeterings;
    return this;
  }

  public NamedMeteringItem addNamedMeteringsItem(NamedMetering namedMeteringsItem) {
    if (this.namedMeterings == null) {
      this.namedMeterings = new ArrayList<NamedMetering>();
    }
    this.namedMeterings.add(namedMeteringsItem);
    return this;
  }

   /**
   * Get namedMeterings
   * @return namedMeterings
  **/
  @Schema(description = "")
  public List<NamedMetering> getNamedMeterings() {
    return namedMeterings;
  }

  public void setNamedMeterings(List<NamedMetering> namedMeterings) {
    this.namedMeterings = namedMeterings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NamedMeteringItem namedMeteringItem = (NamedMeteringItem) o;
    return Objects.equals(this.itemName, namedMeteringItem.itemName) &&
        Objects.equals(this.namedMeterings, namedMeteringItem.namedMeterings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, namedMeterings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NamedMeteringItem {\n");
    
    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    namedMeterings: ").append(toIndentedString(namedMeterings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
