/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/** OneTimeMeteringItem */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class OneTimeMeteringItem {
  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("oneTimeMetering")
  private OneTimeMetering oneTimeMetering = null;

  public OneTimeMeteringItem itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

  /**
   * Get itemName
   *
   * @return itemName
   */
  @Schema(description = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public OneTimeMeteringItem oneTimeMetering(OneTimeMetering oneTimeMetering) {
    this.oneTimeMetering = oneTimeMetering;
    return this;
  }

  /**
   * Get oneTimeMetering
   *
   * @return oneTimeMetering
   */
  @Schema(description = "")
  public OneTimeMetering getOneTimeMetering() {
    return oneTimeMetering;
  }

  public void setOneTimeMetering(OneTimeMetering oneTimeMetering) {
    this.oneTimeMetering = oneTimeMetering;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OneTimeMeteringItem oneTimeMeteringItem = (OneTimeMeteringItem) o;
    return Objects.equals(this.itemName, oneTimeMeteringItem.itemName)
        && Objects.equals(this.oneTimeMetering, oneTimeMeteringItem.oneTimeMetering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, oneTimeMetering);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OneTimeMeteringItem {\n");

    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    oneTimeMetering: ").append(toIndentedString(oneTimeMetering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
