/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.Objects;

/** PolicyFeatureConfig */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class PolicyFeatureConfig {
  @SerializedName("enableDryRun")
  private Boolean enableDryRun = null;

  @SerializedName("enableEnforcementType")
  private Boolean enableEnforcementType = null;

  @SerializedName("enableUpdateNotification")
  private Boolean enableUpdateNotification = null;

  public PolicyFeatureConfig enableDryRun(Boolean enableDryRun) {
    this.enableDryRun = enableDryRun;
    return this;
  }

  /**
   * Get enableDryRun
   *
   * @return enableDryRun
   */
  @Schema(description = "")
  public Boolean isEnableDryRun() {
    return enableDryRun;
  }

  public void setEnableDryRun(Boolean enableDryRun) {
    this.enableDryRun = enableDryRun;
  }

  public PolicyFeatureConfig enableEnforcementType(Boolean enableEnforcementType) {
    this.enableEnforcementType = enableEnforcementType;
    return this;
  }

  /**
   * Get enableEnforcementType
   *
   * @return enableEnforcementType
   */
  @Schema(description = "")
  public Boolean isEnableEnforcementType() {
    return enableEnforcementType;
  }

  public void setEnableEnforcementType(Boolean enableEnforcementType) {
    this.enableEnforcementType = enableEnforcementType;
  }

  public PolicyFeatureConfig enableUpdateNotification(Boolean enableUpdateNotification) {
    this.enableUpdateNotification = enableUpdateNotification;
    return this;
  }

  /**
   * Get enableUpdateNotification
   *
   * @return enableUpdateNotification
   */
  @Schema(description = "")
  public Boolean isEnableUpdateNotification() {
    return enableUpdateNotification;
  }

  public void setEnableUpdateNotification(Boolean enableUpdateNotification) {
    this.enableUpdateNotification = enableUpdateNotification;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PolicyFeatureConfig policyFeatureConfig = (PolicyFeatureConfig) o;
    return Objects.equals(this.enableDryRun, policyFeatureConfig.enableDryRun)
        && Objects.equals(this.enableEnforcementType, policyFeatureConfig.enableEnforcementType)
        && Objects.equals(
            this.enableUpdateNotification, policyFeatureConfig.enableUpdateNotification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enableDryRun, enableEnforcementType, enableUpdateNotification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PolicyFeatureConfig {\n");

    sb.append("    enableDryRun: ").append(toIndentedString(enableDryRun)).append("\n");
    sb.append("    enableEnforcementType: ")
        .append(toIndentedString(enableEnforcementType))
        .append("\n");
    sb.append("    enableUpdateNotification: ")
        .append(toIndentedString(enableUpdateNotification))
        .append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
