/*
 * VMware Service Broker API
 * A multi-cloud API for Cloud Automation Services
 *
 * OpenAPI spec version: 2020-08-25
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.vmware.vra.jenkinsplugin.model.catalog;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/** TagBasedRateFactorItem */
@javax.annotation.Generated(
    value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen",
    date = "2020-09-09T18:27:41.063635-04:00[America/New_York]")
public class TagBasedRateFactorItem {
  @SerializedName("itemName")
  private String itemName = null;

  @SerializedName("rateFactors")
  private List<RateFactorItem> rateFactors = null;

  public TagBasedRateFactorItem itemName(String itemName) {
    this.itemName = itemName;
    return this;
  }

  /**
   * Get itemName
   *
   * @return itemName
   */
  @Schema(description = "")
  public String getItemName() {
    return itemName;
  }

  public void setItemName(String itemName) {
    this.itemName = itemName;
  }

  public TagBasedRateFactorItem rateFactors(List<RateFactorItem> rateFactors) {
    this.rateFactors = rateFactors;
    return this;
  }

  public TagBasedRateFactorItem addRateFactorsItem(RateFactorItem rateFactorsItem) {
    if (this.rateFactors == null) {
      this.rateFactors = new ArrayList<RateFactorItem>();
    }
    this.rateFactors.add(rateFactorsItem);
    return this;
  }

  /**
   * Get rateFactors
   *
   * @return rateFactors
   */
  @Schema(description = "")
  public List<RateFactorItem> getRateFactors() {
    return rateFactors;
  }

  public void setRateFactors(List<RateFactorItem> rateFactors) {
    this.rateFactors = rateFactors;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagBasedRateFactorItem tagBasedRateFactorItem = (TagBasedRateFactorItem) o;
    return Objects.equals(this.itemName, tagBasedRateFactorItem.itemName)
        && Objects.equals(this.rateFactors, tagBasedRateFactorItem.rateFactors);
  }

  @Override
  public int hashCode() {
    return Objects.hash(itemName, rateFactors);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagBasedRateFactorItem {\n");

    sb.append("    itemName: ").append(toIndentedString(itemName)).append("\n");
    sb.append("    rateFactors: ").append(toIndentedString(rateFactors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
