/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.virtualviking.vra.jenkinsplugin.model.iaas.Href;
import net.virtualviking.vra.jenkinsplugin.model.iaas.Tag;

/**
 * State object representing a cloud account.&lt;br&gt;&lt;br&gt;A cloud account identifies a cloud account type and an account-specific deployment region or data center where the associated cloud account resources are hosted.&lt;br&gt;**HATEOAS** links:&lt;br&gt;**associated-cloud-accounts** - array[CloudAccount] - Cloud accounts associated to this cloud account. For example an NSX endpoint linked to a vSphere cloud account.&lt;br&gt;**regions** - array[Region] - List of regions that are enabled for this cloud account.&lt;br&gt;**self** - CloudAccount - Self link to this cloud account
 */
@ApiModel(description = "State object representing a cloud account.<br><br>A cloud account identifies a cloud account type and an account-specific deployment region or data center where the associated cloud account resources are hosted.<br>**HATEOAS** links:<br>**associated-cloud-accounts** - array[CloudAccount] - Cloud accounts associated to this cloud account. For example an NSX endpoint linked to a vSphere cloud account.<br>**regions** - array[Region] - List of regions that are enabled for this cloud account.<br>**self** - CloudAccount - Self link to this cloud account")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class CloudAccount {
  @SerializedName("owner")
  private String owner = null;

  @SerializedName("cloudAccountProperties")
  private Map<String, String> cloudAccountProperties = new HashMap<String, String>();

  @SerializedName("enabledRegionIds")
  private List<String> enabledRegionIds = null;

  @SerializedName("_links")
  private Map<String, Href> links = new HashMap<String, Href>();

  @SerializedName("cloudAccountType")
  private String cloudAccountType = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("orgId")
  private String orgId = null;

  @SerializedName("tags")
  private List<Tag> tags = null;

  @SerializedName("organizationId")
  private String organizationId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("customProperties")
  private Map<String, String> customProperties = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public CloudAccount owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Email of the user that owns the entity.
   * @return owner
  **/
  @ApiModelProperty(example = "csp@vmware.com", value = "Email of the user that owns the entity.")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public CloudAccount cloudAccountProperties(Map<String, String> cloudAccountProperties) {
    this.cloudAccountProperties = cloudAccountProperties;
    return this;
  }

  public CloudAccount putCloudAccountPropertiesItem(String key, String cloudAccountPropertiesItem) {
    this.cloudAccountProperties.put(key, cloudAccountPropertiesItem);
    return this;
  }

   /**
   * Cloud account specific properties
   * @return cloudAccountProperties
  **/
  @ApiModelProperty(example = "\"{ \\\"hostName\\\": \\\"vcenter.mycompany.com\\\" }\"", required = true, value = "Cloud account specific properties")
  public Map<String, String> getCloudAccountProperties() {
    return cloudAccountProperties;
  }

  public void setCloudAccountProperties(Map<String, String> cloudAccountProperties) {
    this.cloudAccountProperties = cloudAccountProperties;
  }

  public CloudAccount enabledRegionIds(List<String> enabledRegionIds) {
    this.enabledRegionIds = enabledRegionIds;
    return this;
  }

  public CloudAccount addEnabledRegionIdsItem(String enabledRegionIdsItem) {
    if (this.enabledRegionIds == null) {
      this.enabledRegionIds = new ArrayList<String>();
    }
    this.enabledRegionIds.add(enabledRegionIdsItem);
    return this;
  }

   /**
   * A set of region names to enable provisioning on.
   * @return enabledRegionIds
  **/
  @ApiModelProperty(example = "\"[ \\\"us-east-1\\\", \\\"ap-northeast-1\\\" ]\"", value = "A set of region names to enable provisioning on.")
  public List<String> getEnabledRegionIds() {
    return enabledRegionIds;
  }

  public void setEnabledRegionIds(List<String> enabledRegionIds) {
    this.enabledRegionIds = enabledRegionIds;
  }

  public CloudAccount links(Map<String, Href> links) {
    this.links = links;
    return this;
  }

  public CloudAccount putLinksItem(String key, Href linksItem) {
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * HATEOAS of the entity
   * @return links
  **/
  @ApiModelProperty(required = true, value = "HATEOAS of the entity")
  public Map<String, Href> getLinks() {
    return links;
  }

  public void setLinks(Map<String, Href> links) {
    this.links = links;
  }

  public CloudAccount cloudAccountType(String cloudAccountType) {
    this.cloudAccountType = cloudAccountType;
    return this;
  }

   /**
   * Cloud account type
   * @return cloudAccountType
  **/
  @ApiModelProperty(example = "vsphere, aws, azure, nsxv, nsxt", required = true, value = "Cloud account type")
  public String getCloudAccountType() {
    return cloudAccountType;
  }

  public void setCloudAccountType(String cloudAccountType) {
    this.cloudAccountType = cloudAccountType;
  }

  public CloudAccount description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A human-friendly description.
   * @return description
  **/
  @ApiModelProperty(example = "my-description", value = "A human-friendly description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CloudAccount orgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

   /**
   * The id of the organization this entity belongs to.
   * @return orgId
  **/
  @ApiModelProperty(example = "9e49", value = "The id of the organization this entity belongs to.")
  public String getOrgId() {
    return orgId;
  }

  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }

  public CloudAccount tags(List<Tag> tags) {
    this.tags = tags;
    return this;
  }

  public CloudAccount addTagsItem(Tag tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<Tag>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * A set of tag keys and optional values that were set on the Cloud Account
   * @return tags
  **/
  @ApiModelProperty(example = "\"[ { \\\"key\\\" : \\\"env\\\", \\\"value\\\": \\\"dev\\\" } ]\"", value = "A set of tag keys and optional values that were set on the Cloud Account")
  public List<Tag> getTags() {
    return tags;
  }

  public void setTags(List<Tag> tags) {
    this.tags = tags;
  }

  public CloudAccount organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.
   * @return organizationId
  **/
  @ApiModelProperty(example = "deprecated", value = "This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public CloudAccount createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date when the entity was created. The date is in ISO 8601 and UTC.
   * @return createdAt
  **/
  @ApiModelProperty(example = "2012-09-27", value = "Date when the entity was created. The date is in ISO 8601 and UTC.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public CloudAccount customProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public CloudAccount putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<String, String>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * Additional properties that may be used to extend the base type.
   * @return customProperties
  **/
  @ApiModelProperty(example = "\"{ \\\"isExternal\\\" : \\\"false\\\" }\"", value = "Additional properties that may be used to extend the base type.")
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }

  public CloudAccount name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-friendly name used as an identifier in APIs that support this option.
   * @return name
  **/
  @ApiModelProperty(example = "my-name", value = "A human-friendly name used as an identifier in APIs that support this option.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CloudAccount id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of this resource instance
   * @return id
  **/
  @ApiModelProperty(example = "9e49", required = true, value = "The id of this resource instance")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CloudAccount updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Date when the entity was last updated. The date is ISO 8601 and UTC.
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2012-09-27", value = "Date when the entity was last updated. The date is ISO 8601 and UTC.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudAccount cloudAccount = (CloudAccount) o;
    return Objects.equals(this.owner, cloudAccount.owner) &&
        Objects.equals(this.cloudAccountProperties, cloudAccount.cloudAccountProperties) &&
        Objects.equals(this.enabledRegionIds, cloudAccount.enabledRegionIds) &&
        Objects.equals(this.links, cloudAccount.links) &&
        Objects.equals(this.cloudAccountType, cloudAccount.cloudAccountType) &&
        Objects.equals(this.description, cloudAccount.description) &&
        Objects.equals(this.orgId, cloudAccount.orgId) &&
        Objects.equals(this.tags, cloudAccount.tags) &&
        Objects.equals(this.organizationId, cloudAccount.organizationId) &&
        Objects.equals(this.createdAt, cloudAccount.createdAt) &&
        Objects.equals(this.customProperties, cloudAccount.customProperties) &&
        Objects.equals(this.name, cloudAccount.name) &&
        Objects.equals(this.id, cloudAccount.id) &&
        Objects.equals(this.updatedAt, cloudAccount.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, cloudAccountProperties, enabledRegionIds, links, cloudAccountType, description, orgId, tags, organizationId, createdAt, customProperties, name, id, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudAccount {\n");
    
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    cloudAccountProperties: ").append(toIndentedString(cloudAccountProperties)).append("\n");
    sb.append("    enabledRegionIds: ").append(toIndentedString(enabledRegionIds)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    cloudAccountType: ").append(toIndentedString(cloudAccountType)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

