/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.virtualviking.vra.jenkinsplugin.model.iaas.NatRule;

/**
 * Compute Gateway Configuration. Applies to NSX cloud accounts only.
 */
@ApiModel(description = "Compute Gateway Configuration. Applies to NSX cloud accounts only.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class ComputeGatewaySpecification {
  @SerializedName("customProperties")
  private Map<String, String> customProperties = null;

  @SerializedName("deploymentId")
  private String deploymentId = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("networks")
  private List<String> networks = new ArrayList<String>();

  @SerializedName("natRules")
  private List<NatRule> natRules = new ArrayList<NatRule>();

  @SerializedName("projectId")
  private String projectId = null;

  public ComputeGatewaySpecification customProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public ComputeGatewaySpecification putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<String, String>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * Additional custom properties that may be used to extend the compute gateway.
   * @return customProperties
  **/
  @ApiModelProperty(value = "Additional custom properties that may be used to extend the compute gateway.")
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }

  public ComputeGatewaySpecification deploymentId(String deploymentId) {
    this.deploymentId = deploymentId;
    return this;
  }

   /**
   * The id of the deployment that is associated with this resource
   * @return deploymentId
  **/
  @ApiModelProperty(example = "123e4567-e89b-12d3-a456-426655440000", value = "The id of the deployment that is associated with this resource")
  public String getDeploymentId() {
    return deploymentId;
  }

  public void setDeploymentId(String deploymentId) {
    this.deploymentId = deploymentId;
  }

  public ComputeGatewaySpecification name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-friendly name used as an identifier in APIs that support this option.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "A human-friendly name used as an identifier in APIs that support this option.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ComputeGatewaySpecification networks(List<String> networks) {
    this.networks = networks;
    return this;
  }

  public ComputeGatewaySpecification addNetworksItem(String networksItem) {
    this.networks.add(networksItem);
    return this;
  }

   /**
   * List of networks
   * @return networks
  **/
  @ApiModelProperty(required = true, value = "List of networks")
  public List<String> getNetworks() {
    return networks;
  }

  public void setNetworks(List<String> networks) {
    this.networks = networks;
  }

  public ComputeGatewaySpecification natRules(List<NatRule> natRules) {
    this.natRules = natRules;
    return this;
  }

  public ComputeGatewaySpecification addNatRulesItem(NatRule natRulesItem) {
    this.natRules.add(natRulesItem);
    return this;
  }

   /**
   * List of NAT Rules
   * @return natRules
  **/
  @ApiModelProperty(required = true, value = "List of NAT Rules")
  public List<NatRule> getNatRules() {
    return natRules;
  }

  public void setNatRules(List<NatRule> natRules) {
    this.natRules = natRules;
  }

  public ComputeGatewaySpecification projectId(String projectId) {
    this.projectId = projectId;
    return this;
  }

   /**
   * The id of the project the current user belongs to.
   * @return projectId
  **/
  @ApiModelProperty(example = "e058", required = true, value = "The id of the project the current user belongs to.")
  public String getProjectId() {
    return projectId;
  }

  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComputeGatewaySpecification computeGatewaySpecification = (ComputeGatewaySpecification) o;
    return Objects.equals(this.customProperties, computeGatewaySpecification.customProperties) &&
        Objects.equals(this.deploymentId, computeGatewaySpecification.deploymentId) &&
        Objects.equals(this.name, computeGatewaySpecification.name) &&
        Objects.equals(this.networks, computeGatewaySpecification.networks) &&
        Objects.equals(this.natRules, computeGatewaySpecification.natRules) &&
        Objects.equals(this.projectId, computeGatewaySpecification.projectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customProperties, deploymentId, name, networks, natRules, projectId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComputeGatewaySpecification {\n");
    
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    deploymentId: ").append(toIndentedString(deploymentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    networks: ").append(toIndentedString(networks)).append("\n");
    sb.append("    natRules: ").append(toIndentedString(natRules)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

