/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.virtualviking.vra.jenkinsplugin.model.iaas.Constraint;
import net.virtualviking.vra.jenkinsplugin.model.iaas.Href;

/**
 * Represents a fabric image from the corresponding cloud end-point with additional cloud configuration script that will be executed on provisioning
 */
@ApiModel(description = "Represents a fabric image from the corresponding cloud end-point with additional cloud configuration script that will be executed on provisioning")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class ImageMappingDescription {
  @SerializedName("owner")
  private String owner = null;

  @SerializedName("cloudConfig")
  private String cloudConfig = null;

  @SerializedName("osFamily")
  private String osFamily = null;

  @SerializedName("_links")
  private Map<String, Href> links = new HashMap<String, Href>();

  @SerializedName("externalRegionId")
  private String externalRegionId = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("externalId")
  private String externalId = null;

  @SerializedName("isPrivate")
  private Boolean isPrivate = null;

  @SerializedName("constraints")
  private List<Constraint> constraints = null;

  @SerializedName("orgId")
  private String orgId = null;

  @SerializedName("organizationId")
  private String organizationId = null;

  @SerializedName("createdAt")
  private String createdAt = null;

  @SerializedName("cloudAccountIds")
  private List<String> cloudAccountIds = null;

  @SerializedName("customProperties")
  private Map<String, String> customProperties = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("updatedAt")
  private String updatedAt = null;

  public ImageMappingDescription owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Email of the user that owns the entity.
   * @return owner
  **/
  @ApiModelProperty(example = "csp@vmware.com", value = "Email of the user that owns the entity.")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public ImageMappingDescription cloudConfig(String cloudConfig) {
    this.cloudConfig = cloudConfig;
    return this;
  }

   /**
   * Cloud config for this image. This cloud config will be merged during provisioning with other cloud configurations such as the bootConfig provided in MachineSpecification.
   * @return cloudConfig
  **/
  @ApiModelProperty(example = "runcmd:   - [\"mkdir\", \"/imageFolder\"]", value = "Cloud config for this image. This cloud config will be merged during provisioning with other cloud configurations such as the bootConfig provided in MachineSpecification.")
  public String getCloudConfig() {
    return cloudConfig;
  }

  public void setCloudConfig(String cloudConfig) {
    this.cloudConfig = cloudConfig;
  }

  public ImageMappingDescription osFamily(String osFamily) {
    this.osFamily = osFamily;
    return this;
  }

   /**
   * Operating System family of the image.
   * @return osFamily
  **/
  @ApiModelProperty(example = "linux, win", value = "Operating System family of the image.")
  public String getOsFamily() {
    return osFamily;
  }

  public void setOsFamily(String osFamily) {
    this.osFamily = osFamily;
  }

  public ImageMappingDescription links(Map<String, Href> links) {
    this.links = links;
    return this;
  }

  public ImageMappingDescription putLinksItem(String key, Href linksItem) {
    this.links.put(key, linksItem);
    return this;
  }

   /**
   * HATEOAS of the entity
   * @return links
  **/
  @ApiModelProperty(required = true, value = "HATEOAS of the entity")
  public Map<String, Href> getLinks() {
    return links;
  }

  public void setLinks(Map<String, Href> links) {
    this.links = links;
  }

  public ImageMappingDescription externalRegionId(String externalRegionId) {
    this.externalRegionId = externalRegionId;
    return this;
  }

   /**
   * The regionId of the image
   * @return externalRegionId
  **/
  @ApiModelProperty(example = "us-east-1", value = "The regionId of the image")
  public String getExternalRegionId() {
    return externalRegionId;
  }

  public void setExternalRegionId(String externalRegionId) {
    this.externalRegionId = externalRegionId;
  }

  public ImageMappingDescription description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A human-friendly description.
   * @return description
  **/
  @ApiModelProperty(example = "my-description", value = "A human-friendly description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ImageMappingDescription externalId(String externalId) {
    this.externalId = externalId;
    return this;
  }

   /**
   * External entity Id on the provider side.
   * @return externalId
  **/
  @ApiModelProperty(example = "i-cfe4-e241-e53b-756a9a2e25d2", value = "External entity Id on the provider side.")
  public String getExternalId() {
    return externalId;
  }

  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  public ImageMappingDescription isPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
    return this;
  }

   /**
   * Indicates whether this fabric image is private. For vSphere, private images are considered to be templates and snapshots and public are Content Library Items
   * @return isPrivate
  **/
  @ApiModelProperty(example = "true", value = "Indicates whether this fabric image is private. For vSphere, private images are considered to be templates and snapshots and public are Content Library Items")
  public Boolean isIsPrivate() {
    return isPrivate;
  }

  public void setIsPrivate(Boolean isPrivate) {
    this.isPrivate = isPrivate;
  }

  public ImageMappingDescription constraints(List<Constraint> constraints) {
    this.constraints = constraints;
    return this;
  }

  public ImageMappingDescription addConstraintsItem(Constraint constraintsItem) {
    if (this.constraints == null) {
      this.constraints = new ArrayList<Constraint>();
    }
    this.constraints.add(constraintsItem);
    return this;
  }

   /**
   * Constraints that are used to drive placement policies for the image that is produced from this mapping.Constraint expressions are matched against tags on existing placement targets.
   * @return constraints
  **/
  @ApiModelProperty(example = "\"[{\\\"mandatory\\\" : \\\"true\\\", \\\"expression\\\": \\\"environment\\\":\\\"prod\\\"}, {\\\"mandatory\\\" : \\\"false\\\", \\\"expression\\\": \\\"pci\\\"}]\"", value = "Constraints that are used to drive placement policies for the image that is produced from this mapping.Constraint expressions are matched against tags on existing placement targets.")
  public List<Constraint> getConstraints() {
    return constraints;
  }

  public void setConstraints(List<Constraint> constraints) {
    this.constraints = constraints;
  }

  public ImageMappingDescription orgId(String orgId) {
    this.orgId = orgId;
    return this;
  }

   /**
   * The id of the organization this entity belongs to.
   * @return orgId
  **/
  @ApiModelProperty(example = "9e49", value = "The id of the organization this entity belongs to.")
  public String getOrgId() {
    return orgId;
  }

  public void setOrgId(String orgId) {
    this.orgId = orgId;
  }

  public ImageMappingDescription organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

   /**
   * This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.
   * @return organizationId
  **/
  @ApiModelProperty(example = "deprecated", value = "This field is deprecated. Use orgId instead. The id of the organization this entity belongs to.")
  public String getOrganizationId() {
    return organizationId;
  }

  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public ImageMappingDescription createdAt(String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Date when the entity was created. The date is in ISO 8601 and UTC.
   * @return createdAt
  **/
  @ApiModelProperty(example = "2012-09-27", value = "Date when the entity was created. The date is in ISO 8601 and UTC.")
  public String getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(String createdAt) {
    this.createdAt = createdAt;
  }

  public ImageMappingDescription cloudAccountIds(List<String> cloudAccountIds) {
    this.cloudAccountIds = cloudAccountIds;
    return this;
  }

  public ImageMappingDescription addCloudAccountIdsItem(String cloudAccountIdsItem) {
    if (this.cloudAccountIds == null) {
      this.cloudAccountIds = new ArrayList<String>();
    }
    this.cloudAccountIds.add(cloudAccountIdsItem);
    return this;
  }

   /**
   * Set of ids of the cloud accounts this entity belongs to.
   * @return cloudAccountIds
  **/
  @ApiModelProperty(example = "\"[9e49]\"", value = "Set of ids of the cloud accounts this entity belongs to.")
  public List<String> getCloudAccountIds() {
    return cloudAccountIds;
  }

  public void setCloudAccountIds(List<String> cloudAccountIds) {
    this.cloudAccountIds = cloudAccountIds;
  }

  public ImageMappingDescription customProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public ImageMappingDescription putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<String, String>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * Additional properties that may be used to extend the base type.
   * @return customProperties
  **/
  @ApiModelProperty(example = "\"{ \\\"prop1\\\" : \\\"value1\\\" }\"", value = "Additional properties that may be used to extend the base type.")
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }

  public ImageMappingDescription name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-friendly name used as an identifier in APIs that support this option.
   * @return name
  **/
  @ApiModelProperty(example = "my-name", value = "A human-friendly name used as an identifier in APIs that support this option.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ImageMappingDescription id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The id of this resource instance
   * @return id
  **/
  @ApiModelProperty(example = "9e49", required = true, value = "The id of this resource instance")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ImageMappingDescription updatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Date when the entity was last updated. The date is ISO 8601 and UTC.
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2012-09-27", value = "Date when the entity was last updated. The date is ISO 8601 and UTC.")
  public String getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(String updatedAt) {
    this.updatedAt = updatedAt;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ImageMappingDescription imageMappingDescription = (ImageMappingDescription) o;
    return Objects.equals(this.owner, imageMappingDescription.owner) &&
        Objects.equals(this.cloudConfig, imageMappingDescription.cloudConfig) &&
        Objects.equals(this.osFamily, imageMappingDescription.osFamily) &&
        Objects.equals(this.links, imageMappingDescription.links) &&
        Objects.equals(this.externalRegionId, imageMappingDescription.externalRegionId) &&
        Objects.equals(this.description, imageMappingDescription.description) &&
        Objects.equals(this.externalId, imageMappingDescription.externalId) &&
        Objects.equals(this.isPrivate, imageMappingDescription.isPrivate) &&
        Objects.equals(this.constraints, imageMappingDescription.constraints) &&
        Objects.equals(this.orgId, imageMappingDescription.orgId) &&
        Objects.equals(this.organizationId, imageMappingDescription.organizationId) &&
        Objects.equals(this.createdAt, imageMappingDescription.createdAt) &&
        Objects.equals(this.cloudAccountIds, imageMappingDescription.cloudAccountIds) &&
        Objects.equals(this.customProperties, imageMappingDescription.customProperties) &&
        Objects.equals(this.name, imageMappingDescription.name) &&
        Objects.equals(this.id, imageMappingDescription.id) &&
        Objects.equals(this.updatedAt, imageMappingDescription.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(owner, cloudConfig, osFamily, links, externalRegionId, description, externalId, isPrivate, constraints, orgId, organizationId, createdAt, cloudAccountIds, customProperties, name, id, updatedAt);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImageMappingDescription {\n");
    
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    cloudConfig: ").append(toIndentedString(cloudConfig)).append("\n");
    sb.append("    osFamily: ").append(toIndentedString(osFamily)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    externalRegionId: ").append(toIndentedString(externalRegionId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    externalId: ").append(toIndentedString(externalId)).append("\n");
    sb.append("    isPrivate: ").append(toIndentedString(isPrivate)).append("\n");
    sb.append("    constraints: ").append(toIndentedString(constraints)).append("\n");
    sb.append("    orgId: ").append(toIndentedString(orgId)).append("\n");
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    cloudAccountIds: ").append(toIndentedString(cloudAccountIds)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

