/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Machine boot config settings that will define how the provisioning will handle the boot config script execution.
 */
@ApiModel(description = "Machine boot config settings that will define how the provisioning will handle the boot config script execution.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class MachineBootConfigSettings {
  @SerializedName("phoneHomeShouldWait")
  private Boolean phoneHomeShouldWait = null;

  @SerializedName("phoneHomeFailOnTimeout")
  private Boolean phoneHomeFailOnTimeout = null;

  @SerializedName("phoneHomeTimeoutSeconds")
  private Integer phoneHomeTimeoutSeconds = null;

  public MachineBootConfigSettings phoneHomeShouldWait(Boolean phoneHomeShouldWait) {
    this.phoneHomeShouldWait = phoneHomeShouldWait;
    return this;
  }

   /**
   * A phone_home module will be added to the Cloud Config and the provisioning will wait on a callback prior proceeding
   * @return phoneHomeShouldWait
  **/
  @ApiModelProperty(example = "true", value = "A phone_home module will be added to the Cloud Config and the provisioning will wait on a callback prior proceeding")
  public Boolean isPhoneHomeShouldWait() {
    return phoneHomeShouldWait;
  }

  public void setPhoneHomeShouldWait(Boolean phoneHomeShouldWait) {
    this.phoneHomeShouldWait = phoneHomeShouldWait;
  }

  public MachineBootConfigSettings phoneHomeFailOnTimeout(Boolean phoneHomeFailOnTimeout) {
    this.phoneHomeFailOnTimeout = phoneHomeFailOnTimeout;
    return this;
  }

   /**
   * In case a timeout occurs whether the provisioning process should fail or continue.
   * @return phoneHomeFailOnTimeout
  **/
  @ApiModelProperty(example = "false", value = "In case a timeout occurs whether the provisioning process should fail or continue.")
  public Boolean isPhoneHomeFailOnTimeout() {
    return phoneHomeFailOnTimeout;
  }

  public void setPhoneHomeFailOnTimeout(Boolean phoneHomeFailOnTimeout) {
    this.phoneHomeFailOnTimeout = phoneHomeFailOnTimeout;
  }

  public MachineBootConfigSettings phoneHomeTimeoutSeconds(Integer phoneHomeTimeoutSeconds) {
    this.phoneHomeTimeoutSeconds = phoneHomeTimeoutSeconds;
    return this;
  }

   /**
   * The period of time to wait for the phone_home module callback to occur
   * @return phoneHomeTimeoutSeconds
  **/
  @ApiModelProperty(example = "100", value = "The period of time to wait for the phone_home module callback to occur")
  public Integer getPhoneHomeTimeoutSeconds() {
    return phoneHomeTimeoutSeconds;
  }

  public void setPhoneHomeTimeoutSeconds(Integer phoneHomeTimeoutSeconds) {
    this.phoneHomeTimeoutSeconds = phoneHomeTimeoutSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineBootConfigSettings machineBootConfigSettings = (MachineBootConfigSettings) o;
    return Objects.equals(this.phoneHomeShouldWait, machineBootConfigSettings.phoneHomeShouldWait) &&
        Objects.equals(this.phoneHomeFailOnTimeout, machineBootConfigSettings.phoneHomeFailOnTimeout) &&
        Objects.equals(this.phoneHomeTimeoutSeconds, machineBootConfigSettings.phoneHomeTimeoutSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneHomeShouldWait, phoneHomeFailOnTimeout, phoneHomeTimeoutSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineBootConfigSettings {\n");
    
    sb.append("    phoneHomeShouldWait: ").append(toIndentedString(phoneHomeShouldWait)).append("\n");
    sb.append("    phoneHomeFailOnTimeout: ").append(toIndentedString(phoneHomeFailOnTimeout)).append("\n");
    sb.append("    phoneHomeTimeoutSeconds: ").append(toIndentedString(phoneHomeTimeoutSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

