/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Specification for attaching nic to machine
 */
@ApiModel(description = "Specification for attaching nic to machine")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class NetworkInterfaceSpecification {
  @SerializedName("addresses")
  private List<String> addresses = null;

  @SerializedName("customProperties")
  private Map<String, String> customProperties = null;

  @SerializedName("securityGroupIds")
  private List<String> securityGroupIds = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("networkId")
  private String networkId = null;

  @SerializedName("deviceIndex")
  private Integer deviceIndex = null;

  public NetworkInterfaceSpecification addresses(List<String> addresses) {
    this.addresses = addresses;
    return this;
  }

  public NetworkInterfaceSpecification addAddressesItem(String addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<String>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * A list of IP addresses allocated or in use by this network interface.
   * @return addresses
  **/
  @ApiModelProperty(example = "\"[ \\\"10.1.2.190\\\" ]\"", value = "A list of IP addresses allocated or in use by this network interface.")
  public List<String> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }

  public NetworkInterfaceSpecification customProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  public NetworkInterfaceSpecification putCustomPropertiesItem(String key, String customPropertiesItem) {
    if (this.customProperties == null) {
      this.customProperties = new HashMap<String, String>();
    }
    this.customProperties.put(key, customPropertiesItem);
    return this;
  }

   /**
   * Additional properties that may be used to extend the base type.
   * @return customProperties
  **/
  @ApiModelProperty(example = "\"{ \\\"awaitIp\\\" : \\\"true\\\" }\"", value = "Additional properties that may be used to extend the base type.")
  public Map<String, String> getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(Map<String, String> customProperties) {
    this.customProperties = customProperties;
  }

  public NetworkInterfaceSpecification securityGroupIds(List<String> securityGroupIds) {
    this.securityGroupIds = securityGroupIds;
    return this;
  }

  public NetworkInterfaceSpecification addSecurityGroupIdsItem(String securityGroupIdsItem) {
    if (this.securityGroupIds == null) {
      this.securityGroupIds = new ArrayList<String>();
    }
    this.securityGroupIds.add(securityGroupIdsItem);
    return this;
  }

   /**
   * A list of security group ids which this network interface will be assigned to.
   * @return securityGroupIds
  **/
  @ApiModelProperty(value = "A list of security group ids which this network interface will be assigned to.")
  public List<String> getSecurityGroupIds() {
    return securityGroupIds;
  }

  public void setSecurityGroupIds(List<String> securityGroupIds) {
    this.securityGroupIds = securityGroupIds;
  }

  public NetworkInterfaceSpecification name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A human-friendly name used as an identifier in APIs that support this option.
   * @return name
  **/
  @ApiModelProperty(value = "A human-friendly name used as an identifier in APIs that support this option.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public NetworkInterfaceSpecification description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A human-friendly description.
   * @return description
  **/
  @ApiModelProperty(value = "A human-friendly description.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public NetworkInterfaceSpecification networkId(String networkId) {
    this.networkId = networkId;
    return this;
  }

   /**
   * Id of the network instance that this network interface plugs into.
   * @return networkId
  **/
  @ApiModelProperty(example = "dcd9", required = true, value = "Id of the network instance that this network interface plugs into.")
  public String getNetworkId() {
    return networkId;
  }

  public void setNetworkId(String networkId) {
    this.networkId = networkId;
  }

  public NetworkInterfaceSpecification deviceIndex(Integer deviceIndex) {
    this.deviceIndex = deviceIndex;
    return this;
  }

   /**
   * The device index of this network interface.
   * @return deviceIndex
  **/
  @ApiModelProperty(example = "1", value = "The device index of this network interface.")
  public Integer getDeviceIndex() {
    return deviceIndex;
  }

  public void setDeviceIndex(Integer deviceIndex) {
    this.deviceIndex = deviceIndex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkInterfaceSpecification networkInterfaceSpecification = (NetworkInterfaceSpecification) o;
    return Objects.equals(this.addresses, networkInterfaceSpecification.addresses) &&
        Objects.equals(this.customProperties, networkInterfaceSpecification.customProperties) &&
        Objects.equals(this.securityGroupIds, networkInterfaceSpecification.securityGroupIds) &&
        Objects.equals(this.name, networkInterfaceSpecification.name) &&
        Objects.equals(this.description, networkInterfaceSpecification.description) &&
        Objects.equals(this.networkId, networkInterfaceSpecification.networkId) &&
        Objects.equals(this.deviceIndex, networkInterfaceSpecification.deviceIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, customProperties, securityGroupIds, name, description, networkId, deviceIndex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkInterfaceSpecification {\n");
    
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("    securityGroupIds: ").append(toIndentedString(securityGroupIds)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    networkId: ").append(toIndentedString(networkId)).append("\n");
    sb.append("    deviceIndex: ").append(toIndentedString(deviceIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

