/*
 * VMware Cloud Assembly IaaS API
 * A multi-cloud IaaS API for Cloud Automation Services
 *
 * OpenAPI spec version: 2019-01-15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.virtualviking.vra.jenkinsplugin.model.iaas;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.virtualviking.vra.jenkinsplugin.model.iaas.TimeBin;

/**
 * TimeSeriesStats
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-09-01T10:54:54.585-04:00")



public class TimeSeriesStats {
  @SerializedName("bins")
  private Map<String, TimeBin> bins = null;

  /**
   * Gets or Sets aggregationType
   */
  @JsonAdapter(AggregationTypeEnum.Adapter.class)
  public enum AggregationTypeEnum {
    AVG("AVG"),
    
    MIN("MIN"),
    
    MAX("MAX"),
    
    SUM("SUM"),
    
    LATEST("LATEST");

    private String value;

    AggregationTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AggregationTypeEnum fromValue(String text) {
      for (AggregationTypeEnum b : AggregationTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AggregationTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AggregationTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AggregationTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AggregationTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("aggregationType")
  private List<AggregationTypeEnum> aggregationType = null;

  @SerializedName("numBins")
  private Integer numBins = null;

  @SerializedName("binDurationMillis")
  private Long binDurationMillis = null;

  public TimeSeriesStats bins(Map<String, TimeBin> bins) {
    this.bins = bins;
    return this;
  }

  public TimeSeriesStats putBinsItem(String key, TimeBin binsItem) {
    if (this.bins == null) {
      this.bins = new HashMap<String, TimeBin>();
    }
    this.bins.put(key, binsItem);
    return this;
  }

   /**
   * Get bins
   * @return bins
  **/
  @ApiModelProperty(value = "")
  public Map<String, TimeBin> getBins() {
    return bins;
  }

  public void setBins(Map<String, TimeBin> bins) {
    this.bins = bins;
  }

  public TimeSeriesStats aggregationType(List<AggregationTypeEnum> aggregationType) {
    this.aggregationType = aggregationType;
    return this;
  }

  public TimeSeriesStats addAggregationTypeItem(AggregationTypeEnum aggregationTypeItem) {
    if (this.aggregationType == null) {
      this.aggregationType = new ArrayList<AggregationTypeEnum>();
    }
    this.aggregationType.add(aggregationTypeItem);
    return this;
  }

   /**
   * Get aggregationType
   * @return aggregationType
  **/
  @ApiModelProperty(value = "")
  public List<AggregationTypeEnum> getAggregationType() {
    return aggregationType;
  }

  public void setAggregationType(List<AggregationTypeEnum> aggregationType) {
    this.aggregationType = aggregationType;
  }

  public TimeSeriesStats numBins(Integer numBins) {
    this.numBins = numBins;
    return this;
  }

   /**
   * Get numBins
   * @return numBins
  **/
  @ApiModelProperty(value = "")
  public Integer getNumBins() {
    return numBins;
  }

  public void setNumBins(Integer numBins) {
    this.numBins = numBins;
  }

  public TimeSeriesStats binDurationMillis(Long binDurationMillis) {
    this.binDurationMillis = binDurationMillis;
    return this;
  }

   /**
   * Get binDurationMillis
   * @return binDurationMillis
  **/
  @ApiModelProperty(value = "")
  public Long getBinDurationMillis() {
    return binDurationMillis;
  }

  public void setBinDurationMillis(Long binDurationMillis) {
    this.binDurationMillis = binDurationMillis;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeSeriesStats timeSeriesStats = (TimeSeriesStats) o;
    return Objects.equals(this.bins, timeSeriesStats.bins) &&
        Objects.equals(this.aggregationType, timeSeriesStats.aggregationType) &&
        Objects.equals(this.numBins, timeSeriesStats.numBins) &&
        Objects.equals(this.binDurationMillis, timeSeriesStats.binDurationMillis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bins, aggregationType, numBins, binDurationMillis);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeSeriesStats {\n");
    
    sb.append("    bins: ").append(toIndentedString(bins)).append("\n");
    sb.append("    aggregationType: ").append(toIndentedString(aggregationType)).append("\n");
    sb.append("    numBins: ").append(toIndentedString(numBins)).append("\n");
    sb.append("    binDurationMillis: ").append(toIndentedString(binDurationMillis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

